### ISSUE TITLE
Can this library be used simply as a move generator?

### ISSUE THREAD

**Issue by lightningdev45** [theemathas/binary_turk#1]
For example, if I have a game in pgn notation can it be used to play through the game and return the fen of a position at a certain point in the game?     In other words does it understand pgn or would I have to use the pgn to build a representation of the move based on the library's internal representation of moves and positions?

**Comment by theemathas** [comment]
Sorry for the late reply.

This engine does not, and probably will not, understand PGN. It only understands [UCI](https://chessprogramming.wikispaces.com/UCI). You can use any chess GUI (such as the ones in the readme) to load a PGN file.

Note, however, that the UCI protocol supports position input using FEN.
