### ISSUE TITLE
How to get this running?

### ISSUE THREAD

**Issue by Quintasan** [theemathas/binary_turk#2]
This might be dumb but I downloaded xboard and added it to the engines list but it does not do anything at all.

**Comment by theemathas** [comment]
Sorry for the late reply.

I cannot help you without any extra information. What does "does not do anything at all" mean? If you just load an engine into xboard with the default settings, all engines would do nothing until you make a move for white.

**Comment by Quintasan** [comment]
Well, yeah. I did add the engine in XBoard and made a move and nothing happened. Then I deleted the configuration and readded it and then it worked. I must have broken something.
